output "network_name"        { value = google_compute_network.vpc.name }
output "network_id"          { value = google_compute_network.vpc.id }
output "network_self_link"   { value = google_compute_network.vpc.self_link }
output "gke_subnet_name"     { value = google_compute_subnetwork.gke.name }
output "gke_subnet_self_link"{ value = google_compute_subnetwork.gke.self_link }
output "tooling_subnet_name" { value = google_compute_subnetwork.tooling.name }
output "tooling_subnet_self_link" { value = google_compute_subnetwork.tooling.self_link }
output "pods_range_name"     { value = "${var.env}-pods" }
output "services_range_name" { value = "${var.env}-services" }
